#!/usr/bin/env python3
"""
Writes AutoDock Vina config text and converts a supplied ΔG to Kd.
Does not run Vina or DiffDock unless those binaries are invoked separately.
"""

import argparse
import logging
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

logging.basicConfig(level=logging.INFO, format="[%(asctime)s] [%(levelname)s] %(message)s")
logger = logging.getLogger("MolecularDocking")

GAS_CONSTANT_R = 1.98720425864083e-3  # kcal / (mol * K)


def generate_vina_grid_box(
    pocket_center: List[float],
    box_size_angstrom: Tuple[float, float, float] = (20.0, 20.0, 20.0),
    exhaustiveness: int = 8,
    num_modes: int = 9,
    energy_range: float = 3.0,
    receptor_pdbqt: str = "receptor.pdbqt",
    ligand_pdbqt: str = "ligand.pdbqt",
) -> str:
    """Generate AutoDock Vina configuration file content."""
    cx, cy, cz = pocket_center
    sx, sy, sz = box_size_angstrom

    config_str = f"""# AutoDock Vina Configuration Generated by BioNexus
receptor = {receptor_pdbqt}
ligand = {ligand_pdbqt}

# Grid Box Center (Angstroms)
center_x = {cx:.3f}
center_y = {cy:.3f}
center_z = {cz:.3f}

# Grid Box Dimensions (Angstroms)
size_x = {sx:.1f}
size_y = {sy:.1f}
size_z = {sz:.1f}

# Search Parameters
exhaustiveness = {exhaustiveness}
num_modes = {num_modes}
energy_range = {energy_range}
"""
    return config_str


def calculate_dissociation_constant(delta_g_kcal_mol: float, temperature_k: float = 298.15) -> Dict[str, Any]:
    """
    Calculate estimated dissociation constant (Kd) from binding free energy Delta G:
      Delta G = R * T * ln(Kd)  =>  Kd = exp(Delta G / (R * T))
    """
    rt = GAS_CONSTANT_R * temperature_k
    kd_molar = np.exp(delta_g_kcal_mol / rt)

    if kd_molar < 1e-9:
        kd_formatted = f"{kd_molar * 1e12:.2f} pM"
    elif kd_molar < 1e-6:
        kd_formatted = f"{kd_molar * 1e9:.2f} nM"
    elif kd_molar < 1e-3:
        kd_formatted = f"{kd_molar * 1e6:.2f} uM"
    else:
        kd_formatted = f"{kd_molar * 1e3:.2f} mM"

    # Potency qualitative classification
    if delta_g_kcal_mol <= -10.0:
        potency = "High Potency (Picomolar / Low Nanomolar)"
    elif delta_g_kcal_mol <= -8.0:
        potency = "Moderate to High Potency (Nanomolar)"
    elif delta_g_kcal_mol <= -6.0:
        potency = "Micromolar Binder (Hit / Lead Candidate)"
    else:
        potency = "Weak / Non-specific Binding"

    return {
        "delta_g_kcal_mol": round(delta_g_kcal_mol, 2),
        "kd_molar": float(kd_molar),
        "kd_formatted": kd_formatted,
        "potency_tier": potency,
    }


def parse_vina_log(log_text: str) -> List[Dict[str, Any]]:
    """Parse output table from AutoDock Vina log."""
    modes = []
    in_table = False

    for line in log_text.splitlines():
        line = line.strip()
        if "mode |   affinity" in line:
            in_table = True
            continue
        if in_table and line.startswith("-----+"):
            continue
        if in_table and line:
            parts = line.split()
            if len(parts) >= 2 and parts[0].isdigit():
                mode_num = int(parts[0])
                affinity = float(parts[1])
                rmsd_lb = float(parts[2]) if len(parts) > 2 else 0.0
                rmsd_ub = float(parts[3]) if len(parts) > 3 else 0.0

                kd_info = calculate_dissociation_constant(affinity)
                modes.append(
                    {
                        "mode": mode_num,
                        "affinity_kcal_mol": affinity,
                        "rmsd_lower_bound": rmsd_lb,
                        "rmsd_upper_bound": rmsd_ub,
                        "estimated_kd": kd_info["kd_formatted"],
                        "potency": kd_info["potency_tier"],
                    }
                )
        elif in_table and not line:
            break

    return modes


def check_lipinski_rule_of_5(
    molecular_weight: float,
    logp: float,
    hbd: int,
    hba: int,
    rotatable_bonds: Optional[int] = None,
    psa: Optional[float] = None,
) -> Dict[str, Any]:
    """Check Lipinski's Rule of 5 and Veber's rule for drug-likeness."""
    violations = []
    if molecular_weight > 500.0:
        violations.append(f"Molecular weight ({molecular_weight:.1f} Da) > 500 Da")
    if logp > 5.0:
        violations.append(f"LogP ({logp:.2f}) > 5.0")
    if hbd > 5:
        violations.append(f"H-bond donors ({hbd}) > 5")
    if hba > 10:
        violations.append(f"H-bond acceptors ({hba}) > 10")

    veber_violations = []
    if rotatable_bonds is not None and rotatable_bonds > 10:
        veber_violations.append(f"Rotatable bonds ({rotatable_bonds}) > 10")
    if psa is not None and psa > 140.0:
        veber_violations.append(f"Polar surface area ({psa:.1f} A^2) > 140 A^2")

    is_druglike = len(violations) <= 1 and len(veber_violations) == 0

    return {
        "is_druglike": is_druglike,
        "lipinski_violations_count": len(violations),
        "lipinski_violations": violations,
        "veber_violations_count": len(veber_violations),
        "veber_violations": veber_violations,
        "verdict": "Passes Drug-Likeness Criteria" if is_druglike else "Violates Drug-Likeness Criteria",
    }


def main():
    parser = argparse.ArgumentParser(description="Molecular Docking Helper")
    parser.add_argument("--center", "-c", nargs=3, type=float, required=True, help="Center X Y Z of binding pocket")
    parser.add_argument("--out-config", "-o", default="vina.config", help="Output Vina config path")

    args = parser.parse_args()
    config_text = generate_vina_grid_box(args.center)
    with open(args.out_config, "w", encoding="utf-8") as f:
        f.write(config_text)
    logger.info(f"Generated Vina config file at {args.out_config}")


if __name__ == "__main__":
    main()
