#!/usr/bin/env python3
"""
Nextflow Cluster & Cloud Execution Profile Generator.
Generates robust, production-ready nextflow.config profiles for:
  - Slurm, PBS/Torque, SGE/UGE, LSF (HPC clusters)
  - AWS Batch, Google Cloud Batch, Azure Batch (Cloud compute)
  - Singularity / Apptainer, Docker, Conda (Container engines)
  - Dynamic resource escalation with auto-retry on Out-Of-Memory (OOM) exit codes.

Usage:
    python cluster_profile_generator.py --executor slurm --partition standard --account bio_lab -o custom.config
    python cluster_profile_generator.py --executor awsbatch --aws-queue arn:aws:batch:... --aws-region us-east-1
    python cluster_profile_generator.py --executor googlebatch --google-region us-central1 --google-project my-project
"""

import argparse
from typing import Optional

NEXTFLOW_CONFIG_HEADER = """/*
========================================================================================
    Nextflow Cluster Execution Profile
    Generated by BioNexus Nextflow Development Toolkit
========================================================================================
*/
"""


def generate_hpc_profile(
    executor: str = "slurm",
    partition: Optional[str] = None,
    account: Optional[str] = None,
    qos: Optional[str] = None,
    max_memory: str = "256.GB",
    max_cpus: int = 64,
    max_time: str = "72.h",
    container_engine: str = "singularity",
    singularity_cache: Optional[str] = None,
    module_load: Optional[str] = None,
) -> str:
    """Generate Nextflow configuration for HPC workload managers."""
    lines = [NEXTFLOW_CONFIG_HEADER]

    # Global resource limits function
    lines.append(
        """
// Global resource limits helper function
def check_max(obj, type) {
    if (type == 'memory') {
        try {
            if (obj.compareTo(params.max_memory as nextflow.util.MemoryUnit) == 1)
                return params.max_memory as nextflow.util.MemoryUnit
            else
                return obj
        } catch (all) {
            println "   ### ERROR ###   Max memory '${params.max_memory}' is not valid! Using default value: $obj"
            return obj
        }
    } else if (type == 'time') {
        try {
            if (obj.compareTo(params.max_time as nextflow.util.Duration) == 1)
                return params.max_time as nextflow.util.Duration
            else
                return obj
        } catch (all) {
            println "   ### ERROR ###   Max time '${params.max_time}' is not valid! Using default value: $obj"
            return obj
        }
    } else if (type == 'cpus') {
        try {
            return Math.min( obj, params.max_cpus as int )
        } catch (all) {
            println "   ### ERROR ###   Max cpus '${params.max_cpus}' is not valid! Using default value: $obj"
            return obj
        }
    }
}

params {
    max_memory = '"""
        + max_memory
        + """'
    max_cpus   = """
        + str(max_cpus)
        + """
    max_time   = '"""
        + max_time
        + """'
}
"""
    )

    # Container engine configuration
    lines.append("// Container engine settings")
    if container_engine.lower() in ("singularity", "apptainer"):
        engine_name = container_engine.lower()
        cache_dir = singularity_cache or "$HOME/.singularity/cache"
        lines.append(f"""{engine_name} {{
    enabled    = true
    autoMounts = true
    cacheDir   = '{cache_dir}'
}}""")
    elif container_engine.lower() == "docker":
        lines.append("""docker {
    enabled    = true
    userEmulation = true
    runOptions = '-u $(id -u):$(id -g)'
}""")
    elif container_engine.lower() == "conda":
        lines.append("""conda {
    enabled = true
    useMamba = true
}""")

    # Process configuration with auto-retry and exponential resource escalation
    lines.append(f"""
process {{
    executor = '{executor}'
    errorStrategy = {{ task.exitStatus in [140, 143, 137, 104, 134, 139] ? 'retry' : 'finish' }}
    maxRetries = 3
    maxErrors  = '-1'

    // Resource defaults with escalation on retry
    cpus   = {{ check_max( 2    * task.attempt, 'cpus'   ) }}
    memory = {{ check_max( 8.GB * task.attempt, 'memory' ) }}
    time   = {{ check_max( 4.h  * task.attempt, 'time'   ) }}
""")

    # HPC Specific Directives
    if executor == "slurm":
        if partition:
            lines.append(f"    queue = '{partition}'")
        cluster_opts = []
        if account:
            cluster_opts.append(f"--account={account}")
        if qos:
            cluster_opts.append(f"--qos={qos}")
        if cluster_opts:
            lines.append(f"    clusterOptions = '{' '.join(cluster_opts)}'")

    elif executor in ("pbs", "torque"):
        if partition:
            lines.append(f"    queue = '{partition}'")
        if account:
            lines.append(f"    clusterOptions = '-A {account}'")

    elif executor in ("sge", "uge"):
        if partition:
            lines.append(f"    queue = '{partition}'")
        if account:
            lines.append(f"    clusterOptions = '-P {account}'")

    elif executor == "lsf":
        if partition:
            lines.append(f"    queue = '{partition}'")
        if account:
            lines.append(f"    clusterOptions = '-P {account}'")

    if module_load:
        lines.append(f"    beforeScript = 'module load {module_load}'")

    # Specific labels for heavy bioinformatics steps
    lines.append("""
    withLabel:process_single {
        cpus   = { check_max( 1                  , 'cpus'    ) }
        memory = { check_max( 6.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 4.h  * task.attempt, 'time'    ) }
    }
    withLabel:process_low {
        cpus   = { check_max( 2     * task.attempt, 'cpus'    ) }
        memory = { check_max( 12.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 4.h   * task.attempt, 'time'    ) }
    }
    withLabel:process_medium {
        cpus   = { check_max( 8     * task.attempt, 'cpus'    ) }
        memory = { check_max( 36.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 8.h   * task.attempt, 'time'    ) }
    }
    withLabel:process_high {
        cpus   = { check_max( 16    * task.attempt, 'cpus'    ) }
        memory = { check_max( 72.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 16.h  * task.attempt, 'time'    ) }
    }
    withLabel:process_long {
        time   = { check_max( 24.h  * task.attempt, 'time'    ) }
    }
    withLabel:process_high_memory {
        memory = { check_max( 128.GB * task.attempt, 'memory' ) }
    }
}
""")
    return "\n".join(lines)


def generate_cloud_profile(
    provider: str = "aws",
    queue_or_region: Optional[str] = None,
    project: Optional[str] = None,
    work_bucket: Optional[str] = None,
) -> str:
    """Generate configuration for AWS Batch or Google Cloud Batch."""
    lines = [NEXTFLOW_CONFIG_HEADER]

    if provider.lower() == "aws":
        lines.append(f"""// AWS Batch execution profile
aws {{
    region = '{queue_or_region or "us-east-1"}'
    batch {{
        cliPath = '/home/ec2-user/miniconda/bin/aws'
    }}
}}

workDir = '{work_bucket or "s3://my-nextflow-bucket/work"}'

process {{
    executor = 'awsbatch'
    queue    = '{queue_or_region or "arn:aws:batch:us-east-1:123456789012:job-queue/high-priority"}'
    errorStrategy = {{ task.exitStatus in [140, 143, 137] ? 'retry' : 'finish' }}
    maxRetries = 2
}}
""")
    elif provider.lower() in ("google", "googlebatch", "gcp"):
        lines.append(f"""// Google Cloud Batch execution profile
google {{
    project  = '{project or "my-gcp-project"}'
    location = '{queue_or_region or "us-central1"}'
    batch {{
        spot = true
    }}
}}

workDir = '{work_bucket or "gs://my-nextflow-bucket/work"}'

process {{
    executor = 'google-batch'
    errorStrategy = {{ task.exitStatus in [140, 143, 137] ? 'retry' : 'finish' }}
    maxRetries = 2
}}
""")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Dynamic Nextflow Cluster Profile Generator (HPC & Cloud)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate Slurm HPC profile with Singularity
  python cluster_profile_generator.py --executor slurm --partition standard --account bio_lab -o nextflow_slurm.config

  # Generate AWS Batch profile
  python cluster_profile_generator.py --executor awsbatch --aws-queue my-batch-queue --work-bucket s3://my-bucket/work

  # Generate Google Cloud Batch profile
  python cluster_profile_generator.py --executor googlebatch --google-project my-proj --google-region us-central1
        """,
    )
    parser.add_argument(
        "--executor", choices=["slurm", "pbs", "sge", "lsf", "awsbatch", "googlebatch"], default="slurm"
    )
    parser.add_argument(
        "--output", "-o", default="nextflow_cluster.config", help="Output file name (default: nextflow_cluster.config)"
    )
    parser.add_argument("--partition", "-p", help="HPC queue/partition name")
    parser.add_argument("--account", "-a", help="HPC allocation account")
    parser.add_argument("--qos", help="Quality of Service (Slurm)")
    parser.add_argument("--max-memory", default="256.GB", help="Max allowed cluster memory (default: 256.GB)")
    parser.add_argument("--max-cpus", type=int, default=64, help="Max allowed cluster CPUs (default: 64)")
    parser.add_argument("--max-time", default="72.h", help="Max allowed execution walltime (default: 72.h)")
    parser.add_argument("--container", choices=["singularity", "apptainer", "docker", "conda"], default="singularity")
    parser.add_argument("--singularity-cache", help="Custom cache directory for Singularity/Apptainer images")
    parser.add_argument(
        "--module-load", help="HPC environment module to load before execution (e.g. 'singularity/3.8.0')"
    )
    parser.add_argument("--aws-queue", help="AWS Batch job queue ARN")
    parser.add_argument("--aws-region", default="us-east-1", help="AWS region")
    parser.add_argument("--google-project", help="Google Cloud project ID")
    parser.add_argument("--google-region", default="us-central1", help="Google Cloud region")
    parser.add_argument("--work-bucket", help="Cloud object storage work directory (s3://... or gs://...)")

    args = parser.parse_args()

    if args.executor == "awsbatch":
        config_text = generate_cloud_profile(
            provider="aws", queue_or_region=args.aws_queue or args.aws_region, work_bucket=args.work_bucket
        )
    elif args.executor == "googlebatch":
        config_text = generate_cloud_profile(
            provider="google",
            queue_or_region=args.google_region,
            project=args.google_project,
            work_bucket=args.work_bucket,
        )
    else:
        config_text = generate_hpc_profile(
            executor=args.executor,
            partition=args.partition,
            account=args.account,
            qos=args.qos,
            max_memory=args.max_memory,
            max_cpus=args.max_cpus,
            max_time=args.max_time,
            container_engine=args.container,
            singularity_cache=args.singularity_cache,
            module_load=args.module_load,
        )

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(config_text)

    print(f"Generated Nextflow cluster configuration: {args.output}")
    print(f"  Executor: {args.executor}")
    print(
        f"  Container Engine: {args.container if args.executor not in ('awsbatch', 'googlebatch') else 'Cloud Native'}"
    )
    print(f"To run your pipeline: nextflow run nf-core/rnaseq -c {args.output} -profile {args.container} ...")


if __name__ == "__main__":
    main()
